version: "3"

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://minesoc:@postgres:5432/minesoc
    container_name: "minesoc"

networks:
  default:
    external:
      name: postgres-default